@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceMessageAlign center

Title Mastermind Protocol Sequence Diagram

Client --> Server: Establish Connection
Server -> Client: OK

||30||

Client -> Server: START
Client <- Server: STARTED

||30||

Client -> Server: TRY rbgy
Client <- Server: ANSWER 1 2

||30||

Client -> Server: TRY rgrb
Client <- Server: FINISHED WON

||30||

Client -> Server: QUIT
Client <-- Server: closes connection

||60||

Client --> Server: Establish Connection
Client <- Server: OK

||30||

Client -> Server: HELP
Client <- Server: SEND "commands"

||30||

Client -> Server: RULES
Client <- Server: SEND "rules"

||30||

Client -> Server: TRY rbgy
Client <- Server: ERROR "game not started"

||30||

Client -> Server: uuuuuuu
Client <- Server: ERROR "invalid command"

||30||

Client -> Server: START a b
Client <- Server: ERROR "invalid command"

||30||

Client -> Server: QUIT
Client <-- Server: closes connection

@enduml